/* Dedicated TEST environment ONLY, after engine deployment. Creates 100
   synthetic rows; does not read RDS data or modify the RDS view. Deploy once.
   Uses Sys_Calendar.Calendar; substitute a trusted 100-row sequence if access
   is unavailable. IDs/fields below are explicitly synthetic test fixtures. */
CREATE MULTISET TABLE DQ_DB.DQ_TEST_NUMERIC
(
    ROW_ID INTEGER NOT NULL,
    FACT_DT DATE,
    X DECIMAL(18,4),
    NULL_ONLY DECIMAL(18,4),
    CONSTANT_VALUE DECIMAL(18,4),
    SINGLE_VALUE DECIMAL(18,4),
    EXACT_AMOUNT DECIMAL(28,10),
    BAD_TEXT VARCHAR(10)
) UNIQUE PRIMARY INDEX (ROW_ID);
INSERT INTO DQ_DB.DQ_TEST_NUMERIC
SELECT N,
       CASE WHEN N<=50 THEN DATE '2000-01-31'
            WHEN N<=75 THEN DATE '2000-02-29'
            WHEN N<100 THEN DATE '2001-01-31' ELSE NULL END,
       CASE WHEN N=1 THEN NULL WHEN N<=6 THEN 0 ELSE 2 END,
       NULL,7,CASE WHEN N=1 THEN 9 ELSE NULL END,
       CAST(9007199254740993.1234567890 AS DECIMAL(28,10)), 'text'
FROM (SELECT calendar_date - DATE '2000-01-01' + 1 AS N
      FROM Sys_Calendar.Calendar
      WHERE calendar_date BETWEEN DATE '2000-01-01' AND DATE '2000-04-09') S;

REPLACE VIEW DQ_DB.DQ_TEST_EMPTY AS SELECT * FROM DQ_DB.DQ_TEST_NUMERIC WHERE 1=0;
INSERT INTO DQ_DB.DQ_PROJECT_CONFIG VALUES ('DQ_TEST','DQ_DB','DQ_TEST_NUMERIC','FACT_DT','ROW_ID','Y');
INSERT INTO DQ_DB.DQ_PROJECT_CONFIG VALUES ('DQ_EMPTY','DQ_DB','DQ_TEST_EMPTY','FACT_DT','ROW_ID','Y');
INSERT INTO DQ_DB.DQ_PROJECT_CONFIG VALUES ('DQ_BAD','DQ_DB','DQ_TEST_NUMERIC','FACT_DT','ROW_ID','Y');
INSERT INTO DQ_DB.DQ_ENGINE_SETTINGS VALUES ('DQ_TEST',1,5,3,2); /* multiple batches */
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_TEST','X','NUMERIC','Y','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_TEST','NULL_ONLY','NUMERIC','Y','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_TEST','CONSTANT_VALUE','NUMERIC','Y','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_TEST','SINGLE_VALUE','NUMERIC','Y','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_TEST','EXACT_AMOUNT','NUMERIC','Y','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_EMPTY','X','NUMERIC','Y','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_BAD','X','NUMERIC','Y','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_BAD','MISSING_NUMERIC','NUMERIC','Y','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_BAD','BAD_TEXT','NUMERIC','Y','Y');

CREATE MULTISET TABLE DQ_DB.DQ_TEST_OVERFLOW
    (ROW_ID INTEGER NOT NULL, FACT_DT DATE, X FLOAT)
UNIQUE PRIMARY INDEX (ROW_ID);
INSERT INTO DQ_DB.DQ_TEST_OVERFLOW VALUES (1,DATE '2000-01-31',1E100);
INSERT INTO DQ_DB.DQ_PROJECT_CONFIG VALUES ('DQ_FAIL','DQ_DB','DQ_TEST_OVERFLOW','FACT_DT','ROW_ID','Y');
INSERT INTO DQ_DB.DQ_FIELD_CONFIG VALUES ('DQ_FAIL','X','NUMERIC','Y','Y');
