/* After 00_create_numeric_fixture.sql. Fresh, reserved fixture run IDs.
   Every assertion query below must return ZERO ROWS. CALL errors/compilation
   failures are failures, never passing evidence. No real RDS fields altered. */
CALL DQ_DB.SP_DQ_RUN_ENGINE('00000000-0000-4000-8000-000000000001','DQ_TEST');
CALL DQ_DB.SP_DQ_RUN_ENGINE('00000000-0000-4000-8000-000000000002','DQ_EMPTY');

SELECT 'required_run_status' AS ASSERTION_NAME
FROM DQ_DB.DQ_RUN_LOG
WHERE RUN_ID IN ('00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002')
  AND STATUS <> 'SUCCEEDED';
SELECT 'missing_run_logs' AS ASSERTION_NAME
FROM (SELECT COUNT(*) AS N FROM DQ_DB.DQ_ENGINE_SETTINGS) AS CHECK_ANCHOR
WHERE 2 <> (SELECT COUNT(*) FROM DQ_DB.DQ_RUN_LOG
WHERE RUN_ID IN ('00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002'));
SELECT 'fixture_result_count' AS ASSERTION_NAME
FROM (SELECT COUNT(*) AS N FROM DQ_DB.DQ_ENGINE_SETTINGS) AS CHECK_ANCHOR
WHERE
  (400 <> (SELECT COUNT(*) FROM DQ_DB.DQ_COMPLETED_RESULT
           WHERE RUN_ID='00000000-0000-4000-8000-000000000001')
   OR 10 <> (SELECT COUNT(*) FROM DQ_DB.DQ_COMPLETED_RESULT
             WHERE RUN_ID='00000000-0000-4000-8000-000000000002'));
/* Eight periods: one overall, three yearly and four monthly. */
SELECT 'overall_X' AS ASSERTION_NAME, METRIC_NAME,METRIC_VALUE,DQ_COLOUR
FROM DQ_DB.DQ_METRIC_RESULT
WHERE RUN_ID='00000000-0000-4000-8000-000000000001' AND FIELD_NAME='X'
  AND PERIOD_LEVEL='OVERALL' AND
  ((METRIC_NAME='TOTAL_COUNT' AND METRIC_VALUE<>100)
   OR (METRIC_NAME='NON_MISSING_COUNT' AND METRIC_VALUE<>99)
   OR (METRIC_NAME='MISSING_COUNT' AND METRIC_VALUE<>1)
   OR (METRIC_NAME='MISSING_RATE_PCT' AND (METRIC_VALUE<>1 OR DQ_COLOUR<>'AMBER'))
   OR (METRIC_NAME='ZERO_COUNT' AND METRIC_VALUE<>5)
   OR (METRIC_NAME='ZERO_RATE_PCT' AND (METRIC_VALUE<>5 OR DQ_COLOUR<>'RED'))
   OR (METRIC_NAME='MINIMUM' AND METRIC_VALUE<>0)
   OR (METRIC_NAME='MAXIMUM' AND METRIC_VALUE<>2)
   OR (METRIC_NAME='MEAN' AND ABS(METRIC_VALUE-188E0/99E0)>0.00000001)
   OR (METRIC_NAME='STDDEV_SAMP'
       AND ABS(METRIC_VALUE-SQRT((376E0-188E0*188E0/99E0)/98E0))>0.00000001)
   OR METRIC_VALUE IS NULL);

SELECT 'special_fields' AS ASSERTION_NAME,FIELD_NAME,METRIC_NAME,METRIC_VALUE
FROM DQ_DB.DQ_METRIC_RESULT
WHERE RUN_ID='00000000-0000-4000-8000-000000000001' AND PERIOD_LEVEL='OVERALL' AND
  ((FIELD_NAME='NULL_ONLY' AND
       ((METRIC_NAME IN ('MINIMUM','MAXIMUM','MEAN','STDDEV_SAMP') AND METRIC_VALUE IS NOT NULL)
        OR (METRIC_NAME='MISSING_COUNT' AND METRIC_VALUE<>100)
        OR (METRIC_NAME='MISSING_RATE_PCT' AND (METRIC_VALUE<>100 OR DQ_COLOUR<>'RED'))))
   OR (FIELD_NAME='CONSTANT_VALUE' AND METRIC_NAME='STDDEV_SAMP' AND (METRIC_VALUE IS NULL OR METRIC_VALUE<>0))
   OR (FIELD_NAME='SINGLE_VALUE' AND METRIC_NAME='STDDEV_SAMP' AND METRIC_VALUE IS NOT NULL)
   OR (FIELD_NAME='EXACT_AMOUNT' AND METRIC_NAME IN ('MINIMUM','MAXIMUM')
       AND (METRIC_VALUE IS NULL OR METRIC_VALUE<>CAST(9007199254740993.1234567890 AS DECIMAL(38,10)))));

SELECT 'empty_source' AS ASSERTION_NAME,METRIC_NAME,METRIC_VALUE,DQ_COLOUR
FROM DQ_DB.DQ_METRIC_RESULT
WHERE RUN_ID='00000000-0000-4000-8000-000000000002' AND
  ((METRIC_NAME IN ('TOTAL_COUNT','NON_MISSING_COUNT','MISSING_COUNT','ZERO_COUNT')
       AND (METRIC_VALUE IS NULL OR METRIC_VALUE<>0))
   OR (METRIC_NAME IN ('MISSING_RATE_PCT','ZERO_RATE_PCT')
       AND (METRIC_VALUE IS NOT NULL OR DQ_COLOUR<>'NOT_EVALUATED'))
   OR (METRIC_NAME IN ('MINIMUM','MAXIMUM','MEAN','STDDEV_SAMP') AND METRIC_VALUE IS NOT NULL)
   OR PERIOD_LEVEL<>'OVERALL');

/* Count reconciliation includes UNKNOWN; statistics are never averaged. */
SELECT 'count_reconciliation' AS ASSERTION_NAME,O.FIELD_NAME,O.METRIC_NAME,P.PERIOD_LEVEL
FROM DQ_DB.DQ_METRIC_RESULT O
JOIN (SELECT RUN_ID,FIELD_NAME,METRIC_NAME,PERIOD_LEVEL,SUM(METRIC_VALUE) AS N
      FROM DQ_DB.DQ_METRIC_RESULT
      WHERE RUN_ID='00000000-0000-4000-8000-000000000001'
        AND PERIOD_LEVEL IN ('YEARLY','MONTHLY')
        AND METRIC_NAME IN ('TOTAL_COUNT','NON_MISSING_COUNT','MISSING_COUNT','ZERO_COUNT')
      GROUP BY 1,2,3,4) P
  ON O.RUN_ID=P.RUN_ID AND O.FIELD_NAME=P.FIELD_NAME AND O.METRIC_NAME=P.METRIC_NAME
WHERE O.PERIOD_LEVEL='OVERALL' AND O.METRIC_VALUE<>P.N;

/* Independent period calculation for X: ordinary GROUP BY, no GROUPING SETS. */
CREATE VOLATILE TABLE QA_EXPECTED
 (PERIOD_LEVEL VARCHAR(8), PERIOD_VALUE VARCHAR(10), TOTAL_N BIGINT,
  NONMISS_N BIGINT, ZERO_N BIGINT, LO DECIMAL(38,10), HI DECIMAL(38,10),
  AV FLOAT, SD FLOAT) ON COMMIT PRESERVE ROWS;
INSERT INTO QA_EXPECTED
SELECT 'OVERALL','ALL',COUNT(*),COUNT(X),SUM(CASE WHEN X=0 THEN 1 ELSE 0 END),
       MIN(X),MAX(X),AVG(CAST(X AS FLOAT)),STDDEV_SAMP(CAST(X AS FLOAT))
FROM DQ_DB.DQ_TEST_NUMERIC;
INSERT INTO QA_EXPECTED
SELECT 'YEARLY',COALESCE(TRIM(CAST(EXTRACT(YEAR FROM FACT_DT) AS CHAR(4))),'UNKNOWN'),
       COUNT(*),COUNT(X),SUM(CASE WHEN X=0 THEN 1 ELSE 0 END),
       MIN(X),MAX(X),AVG(CAST(X AS FLOAT)),STDDEV_SAMP(CAST(X AS FLOAT))
FROM DQ_DB.DQ_TEST_NUMERIC GROUP BY 1,2;
INSERT INTO QA_EXPECTED
SELECT 'MONTHLY',CASE WHEN FACT_DT IS NULL THEN 'UNKNOWN'
       ELSE SUBSTR(CAST(CAST(FACT_DT AS DATE FORMAT 'YYYY-MM-DD') AS CHAR(10)),1,7) END,
       COUNT(*),COUNT(X),SUM(CASE WHEN X=0 THEN 1 ELSE 0 END),
       MIN(X),MAX(X),AVG(CAST(X AS FLOAT)),STDDEV_SAMP(CAST(X AS FLOAT))
FROM DQ_DB.DQ_TEST_NUMERIC GROUP BY 1,2;

SELECT 'period_metric_reconciliation' AS ASSERTION_NAME,
       E.PERIOD_LEVEL,E.PERIOD_VALUE,R.METRIC_NAME
FROM QA_EXPECTED E
CROSS JOIN DQ_DB.DQ_METRIC_DEFINITION M
LEFT JOIN DQ_DB.DQ_METRIC_RESULT R
 ON R.RUN_ID='00000000-0000-4000-8000-000000000001' AND R.FIELD_NAME='X'
 AND R.PERIOD_LEVEL=E.PERIOD_LEVEL AND R.PERIOD_VALUE=E.PERIOD_VALUE
 AND R.METRIC_NAME=M.METRIC_NAME
WHERE M.MODULE_NAME='NUMERIC_BASIC' AND
 (R.RUN_ID IS NULL
  OR COALESCE(ABS(CAST(R.METRIC_VALUE AS FLOAT) -
       CASE M.METRIC_ORDINAL WHEN 1 THEN E.TOTAL_N WHEN 2 THEN E.NONMISS_N
       WHEN 3 THEN E.TOTAL_N-E.NONMISS_N WHEN 4 THEN 100E0*(E.TOTAL_N-E.NONMISS_N)/E.TOTAL_N
       WHEN 5 THEN E.ZERO_N WHEN 6 THEN 100E0*E.ZERO_N/E.TOTAL_N
       WHEN 7 THEN E.LO WHEN 8 THEN E.HI WHEN 9 THEN E.AV WHEN 10 THEN E.SD END),0)>0.00000001
  OR (R.METRIC_VALUE IS NULL AND NOT (M.METRIC_ORDINAL=10 AND E.NONMISS_N<2))
  OR (M.METRIC_ORDINAL=10 AND E.NONMISS_N<2 AND R.METRIC_VALUE IS NOT NULL));
DROP TABLE QA_EXPECTED;
