/* Read-only RDS preflight. Use after configuration seed.
   Supply a real completed run UUID for the final checks. No view alteration. */
SELECT FIELD_TYPE,COUNT(*) AS CONFIGURED_FIELDS
FROM DQ_DB.DQ_FIELD_CONFIG WHERE PROJECT_ID='RDS' GROUP BY 1;
/* Workbook classifications are authoritative; no metadata comparison. */
SELECT PROJECT_ID,FIELD_NAME,FIELD_TYPE,ACTIVE_IND,NUMERIC_BASIC_IND
FROM DQ_DB.DQ_FIELD_CONFIG WHERE PROJECT_ID='RDS'
ORDER BY FIELD_TYPE,FIELD_NAME;

/* Verify candidate account-month key. Nonzero duplicates are an observation,
   not an automatic error. This engine profiles view rows without deduplication. */
SELECT COUNT(*) AS DUPLICATE_KEY_GROUPS,
       COALESCE(SUM(KEY_ROWS-1),0) AS EXTRA_ROWS
FROM (SELECT AGMT_ID,FACT_DT,SUM(CAST(1 AS BIGINT)) AS KEY_ROWS
      FROM LAB_T_ORION_MVT.VW_RDS_PHASE2_FACT
      GROUP BY 1,2 HAVING SUM(CAST(1 AS BIGINT))>1) D;
SELECT COALESCE(SUM(CAST(1 AS BIGINT)),0) AS TOTAL_ROWS,
       COALESCE(SUM(CAST(CASE WHEN AGMT_ID IS NULL THEN 1 ELSE 0 END AS BIGINT)),0) AS NULL_ACCOUNT_ROWS,
       COALESCE(SUM(CAST(CASE WHEN FACT_DT IS NULL THEN 1 ELSE 0 END AS BIGINT)),0) AS NULL_REPORTING_DATE_ROWS,
       MIN(FACT_DT) AS FIRST_DATE,MAX(FACT_DT) AS LAST_DATE
FROM LAB_T_ORION_MVT.VW_RDS_PHASE2_FACT;

/* BALANCE_AMT and ARREARS_AMT are NUMERIC in the supplied workbook.
   Independent baseline for one real field. Compare with OVERALL results.
   All counts use BIGINT sums to avoid COUNT(*) integer-overflow settings. */
SELECT COALESCE(SUM(CAST(1 AS BIGINT)),0) AS TOTAL_COUNT,
       COALESCE(SUM(CAST(CASE WHEN BALANCE_AMT IS NOT NULL THEN 1 ELSE 0 END AS BIGINT)),0) AS NON_MISSING_COUNT,
       COALESCE(SUM(CAST(CASE WHEN BALANCE_AMT IS NULL THEN 1 ELSE 0 END AS BIGINT)),0) AS MISSING_COUNT,
       COALESCE(SUM(CAST(CASE WHEN BALANCE_AMT=0 THEN 1 ELSE 0 END AS BIGINT)),0) AS ZERO_COUNT,
       MIN(BALANCE_AMT) AS MINIMUM,MAX(BALANCE_AMT) AS MAXIMUM,
       AVG(CAST(BALANCE_AMT AS FLOAT)) AS MEAN,
       STDDEV_SAMP(CAST(BALANCE_AMT AS FLOAT)) AS STDDEV_SAMP
FROM LAB_T_ORION_MVT.VW_RDS_PHASE2_FACT;

SELECT * FROM DQ_DB.DQ_RUN_LOG WHERE RUN_ID='REPLACE_WITH_RUN_UUID';
SELECT * FROM DQ_DB.DQ_MODULE_LOG WHERE RUN_ID='REPLACE_WITH_RUN_UUID'
ORDER BY ATTEMPT_NO,BATCH_ID;
SELECT * FROM DQ_DB.DQ_COMPLETED_RESULT
WHERE RUN_ID='REPLACE_WITH_RUN_UUID' AND FIELD_NAME='BALANCE_AMT'
ORDER BY PERIOD_LEVEL,PERIOD_VALUE,METRIC_NAME;

/* Each selected field must have ten metrics at every observed period. */
SELECT FIELD_NAME,PERIOD_LEVEL,PERIOD_VALUE,COUNT(*) AS N
FROM DQ_DB.DQ_COMPLETED_RESULT WHERE RUN_ID='REPLACE_WITH_RUN_UUID'
GROUP BY 1,2,3 HAVING COUNT(*)<>10;
