/* Deploy once into an approved, separate DQ database. Replace DQ_DB globally.
   ANSI object names only; identifiers are validated again before dynamic SQL. */
CREATE MULTISET TABLE DQ_DB.DQ_PROJECT_CONFIG
(
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL,
    SOURCE_DATABASE VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    SOURCE_TABLE VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    REPORTING_DATE_FIELD VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    ACCOUNT_ID_FIELD VARCHAR(128) CHARACTER SET LATIN,
    ACTIVE_IND CHAR(1) NOT NULL DEFAULT 'Y' CHECK (ACTIVE_IND IN ('Y','N'))
) UNIQUE PRIMARY INDEX (PROJECT_ID);

CREATE MULTISET TABLE DQ_DB.DQ_FIELD_CONFIG
(
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL,
    FIELD_NAME VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    FIELD_TYPE VARCHAR(16) CHARACTER SET LATIN NOT NULL
        CHECK (FIELD_TYPE IN ('NUMERIC','CATEGORICAL','DATE','IDENTIFIER')),
    ACTIVE_IND CHAR(1) NOT NULL DEFAULT 'Y' CHECK (ACTIVE_IND IN ('Y','N')),
    NUMERIC_BASIC_IND CHAR(1) NOT NULL DEFAULT 'Y'
        CHECK (NUMERIC_BASIC_IND IN ('Y','N'))
) UNIQUE PRIMARY INDEX (PROJECT_ID, FIELD_NAME);

CREATE MULTISET TABLE DQ_DB.DQ_ENGINE_SETTINGS
(
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL, /* '*' = global */
    GREEN_THRESHOLD DECIMAL(9,4) NOT NULL DEFAULT 1.0000,
    RED_THRESHOLD DECIMAL(9,4) NOT NULL DEFAULT 5.0000,
    OUTLIER_SD_MULTIPLIER DECIMAL(9,4) NOT NULL DEFAULT 3.0000,
    SQL_BATCH_SIZE INTEGER NOT NULL DEFAULT 25,
    CHECK (GREEN_THRESHOLD > 0 AND RED_THRESHOLD > GREEN_THRESHOLD
           AND RED_THRESHOLD <= 100),
    CHECK (SQL_BATCH_SIZE BETWEEN 1 AND 30)
) UNIQUE PRIMARY INDEX (PROJECT_ID);

/* Future interface only: no reference distribution or PSI calculation seeded. */
CREATE MULTISET TABLE DQ_DB.DQ_PSI_REFERENCE_CONFIG
(
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL,
    FIELD_NAME VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    REFERENCE_ID VARCHAR(64) CHARACTER SET LATIN NOT NULL,
    REFERENCE_DATABASE VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    REFERENCE_TABLE VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    CATEGORY_COLUMN VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    PROPORTION_COLUMN VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    ACTIVE_IND CHAR(1) NOT NULL CHECK (ACTIVE_IND IN ('Y','N'))
) UNIQUE PRIMARY INDEX (PROJECT_ID, FIELD_NAME, REFERENCE_ID);

/* Small configuration upload staging, never account-level source data. */
CREATE MULTISET TABLE DQ_DB.DQ_FIELD_CONFIG_STAGE
(
    LOAD_ID CHAR(36) CHARACTER SET LATIN NOT NULL,
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL,
    FIELD_NAME VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    FIELD_TYPE VARCHAR(16) CHARACTER SET LATIN NOT NULL
) UNIQUE PRIMARY INDEX (LOAD_ID, PROJECT_ID, FIELD_NAME);

/* Metric metadata is shared by the SQL module and result classification. */
CREATE MULTISET TABLE DQ_DB.DQ_METRIC_DEFINITION
(
    MODULE_NAME VARCHAR(32) CHARACTER SET LATIN NOT NULL,
    METRIC_ORDINAL INTEGER NOT NULL,
    METRIC_NAME VARCHAR(32) CHARACTER SET LATIN NOT NULL,
    IS_PERCENTAGE CHAR(1) NOT NULL CHECK (IS_PERCENTAGE IN ('Y','N'))
) UNIQUE PRIMARY INDEX (MODULE_NAME, METRIC_ORDINAL);
