CREATE MULTISET TABLE DQ_DB.DQ_RUN_LOG
(
    RUN_ID CHAR(36) CHARACTER SET LATIN NOT NULL,
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL,
    START_TIME TIMESTAMP(6) NOT NULL,
    END_TIME TIMESTAMP(6),
    STATUS VARCHAR(16) CHARACTER SET LATIN NOT NULL
        CHECK (STATUS IN ('RUNNING','SUCCEEDED','FAILED')),
    ERROR_CODE INTEGER,
    ERROR_INFORMATION VARCHAR(2048) CHARACTER SET UNICODE,
    SOURCE_DATABASE VARCHAR(128) CHARACTER SET LATIN,
    SOURCE_TABLE VARCHAR(128) CHARACTER SET LATIN,
    REPORTING_DATE_FIELD VARCHAR(128) CHARACTER SET LATIN,
    GREEN_THRESHOLD DECIMAL(9,4),
    RED_THRESHOLD DECIMAL(9,4),
    SQL_BATCH_SIZE INTEGER,
    ATTEMPT_NO INTEGER NOT NULL DEFAULT 1
) UNIQUE PRIMARY INDEX (RUN_ID);

CREATE MULTISET TABLE DQ_DB.DQ_MODULE_LOG
(
    RUN_ID CHAR(36) CHARACTER SET LATIN NOT NULL,
    MODULE_NAME VARCHAR(32) CHARACTER SET LATIN NOT NULL,
    ATTEMPT_NO INTEGER NOT NULL,
    BATCH_ID INTEGER NOT NULL, /* 0 = module summary; 1..n = field batches */
    START_TIME TIMESTAMP(6) NOT NULL,
    END_TIME TIMESTAMP(6),
    STATUS VARCHAR(16) CHARACTER SET LATIN NOT NULL,
    ERROR_CODE INTEGER,
    ERROR_INFORMATION VARCHAR(2048) CHARACTER SET UNICODE,
    FIELD_COUNT INTEGER,
    SQL_TEXT VARCHAR(32000) CHARACTER SET UNICODE /* aggregate query for EXPLAIN */
) PRIMARY INDEX (RUN_ID)
UNIQUE INDEX (RUN_ID, MODULE_NAME, ATTEMPT_NO, BATCH_ID);
