/* Additive migration for EXISTING installations. Deploy once after setup
   tables 00..02; replace DQ_DB globally. Never rerun seed or drop active config.
   These staging tables contain small configuration only, not customer rows. */
CREATE MULTISET TABLE DQ_DB.DQ_PROJECT_CONFIG_XLS_STAGE
(
    LOAD_ID CHAR(36) CHARACTER SET LATIN NOT NULL,
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL,
    SOURCE_DATABASE VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    SOURCE_TABLE VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    REPORTING_DATE_FIELD VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    ACCOUNT_ID_FIELD VARCHAR(128) CHARACTER SET LATIN,
    ACTIVE_IND CHAR(1) NOT NULL CHECK (ACTIVE_IND IN ('Y','N'))
) UNIQUE PRIMARY INDEX (LOAD_ID,PROJECT_ID);
CREATE MULTISET TABLE DQ_DB.DQ_FIELD_CONFIG_XLS_STAGE
(
    LOAD_ID CHAR(36) CHARACTER SET LATIN NOT NULL,
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL,
    FIELD_NAME VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    FIELD_TYPE VARCHAR(16) CHARACTER SET LATIN NOT NULL
        CHECK (FIELD_TYPE IN ('NUMERIC','CATEGORICAL','DATE','IDENTIFIER')),
    ACTIVE_IND CHAR(1) NOT NULL CHECK (ACTIVE_IND IN ('Y','N')),
    NUMERIC_BASIC_IND CHAR(1) NOT NULL CHECK (NUMERIC_BASIC_IND IN ('Y','N'))
) UNIQUE PRIMARY INDEX (LOAD_ID,PROJECT_ID,FIELD_NAME);
CREATE MULTISET TABLE DQ_DB.DQ_SETTINGS_XLS_STAGE
(
    LOAD_ID CHAR(36) CHARACTER SET LATIN NOT NULL,
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN NOT NULL,
    GREEN_THRESHOLD DECIMAL(9,4) NOT NULL,
    RED_THRESHOLD DECIMAL(9,4) NOT NULL,
    SQL_BATCH_SIZE INTEGER NOT NULL,
    OUTLIER_SD_MULTIPLIER DECIMAL(9,4) NOT NULL,
    CHECK (GREEN_THRESHOLD>0 AND RED_THRESHOLD>GREEN_THRESHOLD AND RED_THRESHOLD<=100),
    CHECK (SQL_BATCH_SIZE BETWEEN 1 AND 30),
    CHECK (OUTLIER_SD_MULTIPLIER>0)
) UNIQUE PRIMARY INDEX (LOAD_ID,PROJECT_ID);
CREATE MULTISET TABLE DQ_DB.DQ_CONFIG_LOAD_LOG
(
    LOAD_ID CHAR(36) CHARACTER SET LATIN NOT NULL,
    PROJECT_ID VARCHAR(30) CHARACTER SET LATIN, /* Unknown if staged workbook is incomplete. */
    START_TIME TIMESTAMP(6) NOT NULL,
    END_TIME TIMESTAMP(6),
    STATUS VARCHAR(16) CHARACTER SET LATIN NOT NULL
        CHECK (STATUS IN ('LOADING','APPLIED','FAILED')),
    FIELD_COUNT INTEGER,
    ERROR_INFORMATION VARCHAR(2048) CHARACTER SET UNICODE
) UNIQUE PRIMARY INDEX (LOAD_ID);
