/* Deploy after 06. Submit this whole file as one procedure statement.
   Call in Teradata session mode WITHOUT an enclosing transaction.
   Workbook classifications are trusted; only schema-safe identifiers, logical
   types, flags, row counts and settings are checked. No physical type lookup.
   All three active configuration merges commit together. Absent fields remain
   unchanged; explicit ACTIVE_IND=N deactivates a field. Historical results
   and existing global settings/other projects are never changed here. */
REPLACE PROCEDURE DQ_DB.SP_DQ_APPLY_CONFIG
    (IN P_LOAD_ID CHAR(36))
SQL SECURITY INVOKER
main: BEGIN
    DECLARE V_PROJECT_ID VARCHAR(30);
    DECLARE V_COUNT INTEGER;
    DECLARE V_FIELDS INTEGER;
    DECLARE V_OWNED INTEGER DEFAULT 0;
    DECLARE V_IN_TX INTEGER DEFAULT 0;
    DECLARE V_APPLIED INTEGER DEFAULT 0;
    DECLARE V_ROLLBACK_IGNORED INTEGER DEFAULT 0;
    DECLARE V_ERROR VARCHAR(2048) CHARACTER SET UNICODE;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS EXCEPTION 1 V_ERROR = MESSAGE_TEXT;
        IF V_OWNED = 1 THEN
            IF V_IN_TX = 1 THEN
                /* Some errors already abort a Teradata transaction. Ignore
                   only a redundant rollback error, retaining original text. */
                BEGIN
                    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
                        SET V_ROLLBACK_IGNORED = 1;
                    ROLLBACK;
                END;
            END IF;
            IF V_APPLIED = 1 THEN
                UPDATE DQ_DB.DQ_CONFIG_LOAD_LOG
                   SET ERROR_INFORMATION = SUBSTR('Configuration committed; staging cleanup error: ' || V_ERROR,1,2048)
                 WHERE LOAD_ID = P_LOAD_ID;
            ELSE
                UPDATE DQ_DB.DQ_CONFIG_LOAD_LOG
                   SET STATUS='FAILED',PROJECT_ID=V_PROJECT_ID,END_TIME=CURRENT_TIMESTAMP(6),ERROR_INFORMATION=V_ERROR
                 WHERE LOAD_ID = P_LOAD_ID;
            END IF;
        ELSE
            RESIGNAL;
        END IF;
    END;
    IF REGEXP_SIMILAR(TRIM(P_LOAD_ID),
       '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$','c') <> 1
       THEN
        SIGNAL SQLSTATE 'U0020' SET MESSAGE_TEXT='Invalid configuration load UUID or project';
    END IF;
    INSERT INTO DQ_DB.DQ_CONFIG_LOAD_LOG (LOAD_ID,START_TIME,STATUS)
    VALUES (P_LOAD_ID,CURRENT_TIMESTAMP(6),'LOADING');
    SET V_OWNED = 1;
    BEGIN TRANSACTION;
    SET V_IN_TX = 1;
    SELECT COUNT(*) INTO V_COUNT FROM DQ_DB.DQ_PROJECT_CONFIG_XLS_STAGE
     WHERE LOAD_ID=P_LOAD_ID;
    IF V_COUNT<>1 THEN
        SIGNAL SQLSTATE 'U0022' SET MESSAGE_TEXT='Project sheet requires exactly one staged row';
    END IF;
    SELECT PROJECT_ID INTO V_PROJECT_ID FROM DQ_DB.DQ_PROJECT_CONFIG_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID;
    IF REGEXP_SIMILAR(V_PROJECT_ID,'^[A-Za-z_][A-Za-z0-9_]{0,29}$','c')<>1 THEN
        SIGNAL SQLSTATE 'U0020' SET MESSAGE_TEXT='Invalid project identifier in workbook';
    END IF;
    UPDATE DQ_DB.DQ_CONFIG_LOAD_LOG SET PROJECT_ID=V_PROJECT_ID WHERE LOAD_ID=P_LOAD_ID;
    /* Prevent a run starting during config application; reject active runs.
       Brief table lock also serialises config applies. No request is killed. */
    LOCKING TABLE DQ_DB.DQ_RUN_LOG FOR WRITE
    SELECT COUNT(*) INTO V_COUNT FROM DQ_DB.DQ_RUN_LOG
     WHERE PROJECT_ID=V_PROJECT_ID AND STATUS='RUNNING';
    IF V_COUNT>0 THEN
        SIGNAL SQLSTATE 'U0021' SET MESSAGE_TEXT='Project has a running profile; load configuration after it finishes';
    END IF;
    SELECT COUNT(*) INTO V_COUNT FROM DQ_DB.DQ_PROJECT_CONFIG_XLS_STAGE
     WHERE LOAD_ID=P_LOAD_ID AND
       (PROJECT_ID<>V_PROJECT_ID
        OR REGEXP_SIMILAR(SOURCE_DATABASE,'^[A-Za-z_][A-Za-z0-9_]*$','c')<>1
        OR REGEXP_SIMILAR(SOURCE_TABLE,'^[A-Za-z_][A-Za-z0-9_]*$','c')<>1
        OR REGEXP_SIMILAR(REPORTING_DATE_FIELD,'^[A-Za-z_][A-Za-z0-9_]*$','c')<>1
        OR (ACCOUNT_ID_FIELD IS NOT NULL AND TRIM(ACCOUNT_ID_FIELD)<>'' AND
            REGEXP_SIMILAR(ACCOUNT_ID_FIELD,'^[A-Za-z_][A-Za-z0-9_]*$','c')<>1));
    IF V_COUNT>0 THEN
        SIGNAL SQLSTATE 'U0023' SET MESSAGE_TEXT='Invalid staged project identifiers';
    END IF;
    SELECT COUNT(*) INTO V_FIELDS FROM DQ_DB.DQ_FIELD_CONFIG_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID;
    IF V_FIELDS=0 THEN
        SIGNAL SQLSTATE 'U0024' SET MESSAGE_TEXT='Fields sheet must not be empty';
    END IF;
    SELECT COUNT(*) INTO V_COUNT FROM DQ_DB.DQ_FIELD_CONFIG_XLS_STAGE
     WHERE LOAD_ID=P_LOAD_ID AND
       (PROJECT_ID<>V_PROJECT_ID
        OR REGEXP_SIMILAR(FIELD_NAME,'^[A-Za-z_][A-Za-z0-9_]*$','c')<>1
        OR (FIELD_TYPE<>'NUMERIC' AND NUMERIC_BASIC_IND='Y'));
    IF V_COUNT>0 THEN
        SIGNAL SQLSTATE 'U0025' SET MESSAGE_TEXT='Invalid staged field identifiers or eligibility';
    END IF;
    SELECT COUNT(*) INTO V_COUNT FROM DQ_DB.DQ_SETTINGS_XLS_STAGE
     WHERE LOAD_ID=P_LOAD_ID AND PROJECT_ID=V_PROJECT_ID;
    IF V_COUNT<>1 THEN
        SIGNAL SQLSTATE 'U0026' SET MESSAGE_TEXT='Settings sheet requires one project settings row';
    END IF;
    SELECT COUNT(*) INTO V_COUNT FROM DQ_DB.DQ_SETTINGS_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID;
    IF V_COUNT<>1 THEN
        SIGNAL SQLSTATE 'U0026' SET MESSAGE_TEXT='Unexpected extra settings rows for load';
    END IF;
    MERGE INTO DQ_DB.DQ_PROJECT_CONFIG AS T
    USING (SELECT PROJECT_ID,SOURCE_DATABASE,SOURCE_TABLE,REPORTING_DATE_FIELD,
                  NULLIF(TRIM(ACCOUNT_ID_FIELD),'') AS ACCOUNT_ID_FIELD,ACTIVE_IND
           FROM DQ_DB.DQ_PROJECT_CONFIG_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID) AS S
    ON T.PROJECT_ID=S.PROJECT_ID
    WHEN MATCHED THEN UPDATE SET SOURCE_DATABASE=S.SOURCE_DATABASE,SOURCE_TABLE=S.SOURCE_TABLE,
        REPORTING_DATE_FIELD=S.REPORTING_DATE_FIELD,ACCOUNT_ID_FIELD=S.ACCOUNT_ID_FIELD,ACTIVE_IND=S.ACTIVE_IND
    WHEN NOT MATCHED THEN INSERT (PROJECT_ID,SOURCE_DATABASE,SOURCE_TABLE,REPORTING_DATE_FIELD,ACCOUNT_ID_FIELD,ACTIVE_IND)
        VALUES (S.PROJECT_ID,S.SOURCE_DATABASE,S.SOURCE_TABLE,S.REPORTING_DATE_FIELD,S.ACCOUNT_ID_FIELD,S.ACTIVE_IND);
    MERGE INTO DQ_DB.DQ_FIELD_CONFIG AS T
    USING (SELECT PROJECT_ID,FIELD_NAME,FIELD_TYPE,ACTIVE_IND,NUMERIC_BASIC_IND
           FROM DQ_DB.DQ_FIELD_CONFIG_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID) AS S
    ON T.PROJECT_ID=S.PROJECT_ID AND T.FIELD_NAME=S.FIELD_NAME
    WHEN MATCHED THEN UPDATE SET FIELD_TYPE=S.FIELD_TYPE,ACTIVE_IND=S.ACTIVE_IND,NUMERIC_BASIC_IND=S.NUMERIC_BASIC_IND
    WHEN NOT MATCHED THEN INSERT (PROJECT_ID,FIELD_NAME,FIELD_TYPE,ACTIVE_IND,NUMERIC_BASIC_IND)
        VALUES (S.PROJECT_ID,S.FIELD_NAME,S.FIELD_TYPE,S.ACTIVE_IND,S.NUMERIC_BASIC_IND);
    MERGE INTO DQ_DB.DQ_ENGINE_SETTINGS AS T
    USING (SELECT PROJECT_ID,GREEN_THRESHOLD,RED_THRESHOLD,SQL_BATCH_SIZE,OUTLIER_SD_MULTIPLIER
           FROM DQ_DB.DQ_SETTINGS_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID) AS S
    ON T.PROJECT_ID=S.PROJECT_ID
    WHEN MATCHED THEN UPDATE SET GREEN_THRESHOLD=S.GREEN_THRESHOLD,RED_THRESHOLD=S.RED_THRESHOLD,
        SQL_BATCH_SIZE=S.SQL_BATCH_SIZE,OUTLIER_SD_MULTIPLIER=S.OUTLIER_SD_MULTIPLIER
    WHEN NOT MATCHED THEN INSERT (PROJECT_ID,GREEN_THRESHOLD,RED_THRESHOLD,SQL_BATCH_SIZE,OUTLIER_SD_MULTIPLIER)
        VALUES (S.PROJECT_ID,S.GREEN_THRESHOLD,S.RED_THRESHOLD,S.SQL_BATCH_SIZE,S.OUTLIER_SD_MULTIPLIER);
    UPDATE DQ_DB.DQ_CONFIG_LOAD_LOG
       SET STATUS='APPLIED',END_TIME=CURRENT_TIMESTAMP(6),FIELD_COUNT=V_FIELDS
     WHERE LOAD_ID=P_LOAD_ID;
    END TRANSACTION;
    SET V_IN_TX = 0;
    SET V_APPLIED = 1;
    DELETE FROM DQ_DB.DQ_PROJECT_CONFIG_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID;
    DELETE FROM DQ_DB.DQ_FIELD_CONFIG_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID;
    DELETE FROM DQ_DB.DQ_SETTINGS_XLS_STAGE WHERE LOAD_ID=P_LOAD_ID;
END main;
