/* Shared run lifecycle, Phase 2 selection = Numeric Basic only.
   Future modules belong between run registration and final classification.
   Deploy AFTER SP_DQ_NUMERIC_BASIC and SP_DQ_CLASSIFY. Call in Teradata mode,
   without an explicit enclosing transaction. */
REPLACE PROCEDURE DQ_DB.SP_DQ_RUN_ENGINE
    (IN P_RUN_ID CHAR(36), IN P_PROJECT_ID VARCHAR(30))
SQL SECURITY INVOKER
main: BEGIN
    DECLARE V_COUNT INTEGER;
    DECLARE V_OWNED INTEGER DEFAULT 0;
    DECLARE V_STATUS VARCHAR(16);
    DECLARE V_ERROR VARCHAR(2048) CHARACTER SET UNICODE;
    DECLARE V_ERROR_CODE INTEGER;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS EXCEPTION 1 V_ERROR = MESSAGE_TEXT;
        SET V_ERROR_CODE = SQLCODE;
        IF V_OWNED = 1 THEN
            DELETE FROM DQ_DB.DQ_METRIC_RESULT WHERE RUN_ID = P_RUN_ID;
            UPDATE DQ_DB.DQ_MODULE_LOG
               SET STATUS = 'FAILED',END_TIME = CURRENT_TIMESTAMP(6),
                   ERROR_CODE = V_ERROR_CODE,ERROR_INFORMATION = V_ERROR
             WHERE RUN_ID = P_RUN_ID AND STATUS = 'RUNNING';
            UPDATE DQ_DB.DQ_RUN_LOG
               SET STATUS = 'FAILED',END_TIME = CURRENT_TIMESTAMP(6),
                   ERROR_CODE = V_ERROR_CODE,ERROR_INFORMATION = V_ERROR
             WHERE RUN_ID = P_RUN_ID;
        ELSE
            RESIGNAL;
        END IF;
    END;
    IF REGEXP_SIMILAR(TRIM(P_RUN_ID),
       '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$','c') <> 1
       OR REGEXP_SIMILAR(TRIM(P_PROJECT_ID),'^[A-Za-z_][A-Za-z0-9_]{0,29}$','c') <> 1 THEN
        SIGNAL SQLSTATE 'U0001' SET MESSAGE_TEXT = 'Invalid run UUID or project identifier';
    END IF;
    SELECT COUNT(*) INTO V_COUNT FROM DQ_DB.DQ_RUN_LOG WHERE RUN_ID = P_RUN_ID;
    IF V_COUNT = 0 THEN
        INSERT INTO DQ_DB.DQ_RUN_LOG
          (RUN_ID,PROJECT_ID,START_TIME,STATUS,ATTEMPT_NO)
        VALUES (P_RUN_ID,P_PROJECT_ID,CURRENT_TIMESTAMP(6),'RUNNING',1);
        SET V_OWNED = 1;
    ELSE
        UPDATE DQ_DB.DQ_RUN_LOG
           SET STATUS = 'RUNNING',END_TIME = NULL,ERROR_CODE = NULL,
               ERROR_INFORMATION = NULL,ATTEMPT_NO = ATTEMPT_NO + 1
         WHERE RUN_ID = P_RUN_ID AND PROJECT_ID = P_PROJECT_ID AND STATUS = 'FAILED';
        IF ACTIVITY_COUNT <> 1 THEN
            SIGNAL SQLSTATE 'U0002' SET MESSAGE_TEXT = 'Run is completed, active, or belongs to another project';
        END IF;
        SET V_OWNED = 1;
    END IF;
    CALL DQ_DB.SP_DQ_NUMERIC_BASIC(P_RUN_ID,P_PROJECT_ID);
    SELECT STATUS INTO V_STATUS FROM DQ_DB.DQ_RUN_LOG WHERE RUN_ID = P_RUN_ID;
    IF V_STATUS <> 'RUNNING' THEN
        LEAVE main; /* Module handler recorded failure; never overwrite it. */
    END IF;
    CALL DQ_DB.SP_DQ_CLASSIFY(P_RUN_ID);
    UPDATE DQ_DB.DQ_RUN_LOG SET STATUS='SUCCEEDED',END_TIME=CURRENT_TIMESTAMP(6)
     WHERE RUN_ID = P_RUN_ID AND STATUS='RUNNING';
END main;
